In [2]:
sample_dict={1:"guna",2:"rama",3:"chandra",4:"rao"}
sample_dict

{1: 'guna', 2: 'rama', 3: 'chandra', 4: 'rao'}

In [3]:
sample_dict={1:"guna",2:"rama",3:"chandra",4:"rao",1:"annavarapu"}
sample_dict

{1: 'annavarapu', 2: 'rama', 3: 'chandra', 4: 'rao'}

In [4]:
sample_dict={a:"guna",b:"rama",c:"chandra",d:"rao"}
sample_dict

NameError: name 'a' is not defined

In [9]:
import numpy as np
import pandas as pd
arr=np.arange(1,100)
arr
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.random.randint(20,56,100)

array([35, 23, 39, 25, 27, 22, 27, 28, 49, 27, 20, 40, 37, 52, 38, 35, 48,
       31, 38, 28, 43, 32, 40, 25, 27, 36, 25, 22, 24, 47, 21, 50, 24, 32,
       20, 29, 42, 54, 55, 46, 26, 24, 38, 42, 50, 44, 51, 44, 24, 48, 31,
       50, 31, 40, 27, 25, 35, 48, 29, 54, 34, 48, 37, 38, 55, 38, 21, 29,
       39, 21, 43, 36, 39, 35, 20, 49, 24, 36, 27, 44, 31, 22, 44, 53, 37,
       38, 52, 37, 43, 42, 29, 34, 52, 49, 38, 36, 38, 28, 39, 45])

In [28]:
s=np.arange(30)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [32]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(2,3)

array([[0.25655111, 0.11425214, 0.37177572],
       [0.14023829, 0.18081317, 0.57867226]])

In [35]:
np.random.randn(2,3)

array([[-1.15201951,  2.18490973, -0.12176773],
       [ 0.14198832, -1.52877073, -1.08576122]])

In [36]:
np.random.randint(1,10)

4

In [37]:
np.random.randint(1,10,9)

array([4, 4, 6, 4, 8, 1, 4, 2, 6])

In [38]:
np.random.randint(1,10,100)

array([8, 5, 9, 2, 6, 9, 2, 5, 6, 6, 1, 3, 6, 9, 4, 9, 6, 4, 4, 8, 5, 9,
       9, 8, 7, 8, 4, 6, 5, 9, 1, 2, 2, 6, 1, 2, 6, 6, 6, 2, 6, 8, 8, 3,
       6, 8, 1, 7, 9, 8, 6, 4, 9, 2, 1, 6, 8, 2, 1, 6, 6, 5, 2, 6, 1, 6,
       7, 2, 7, 1, 3, 3, 5, 8, 2, 3, 1, 1, 9, 3, 2, 7, 6, 4, 7, 6, 2, 1,
       3, 3, 1, 9, 5, 6, 4, 8, 1, 3, 2, 5])

In [40]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr[2:5]

[3, 4, 5]

In [43]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr[8]

9

In [47]:
arr=np.arange(1,21)
arr[1:4]=100
arr

array([  1, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [11]:
import numpy as np
arr=np.array(([1,2,3,4],[3,4,5,6],[6,7,8,9]))#creating matrix
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [12]:
arr[1,2]#extracting the element by using row and column

5

In [13]:
arr[2,:]#row selection

array([6, 7, 8, 9])

In [14]:
arr[2]#row selection

array([6, 7, 8, 9])

In [15]:
arr[:,(3,2)]#slicing

array([[4, 3],
       [6, 5],
       [9, 8]])

# selection techniques


In [4]:
k=np.arange(1,20)#arrange an array 
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
k+k#concatination of an array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [5]:
np.argmax(k)#maximum index value

18

In [22]:
np.argmin(k)#minimum index value

0

In [17]:
np.exp(k)#exponential values

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [18]:
np.sqrt(k)#square roor values

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [19]:
np.min(k)#minimum value

1

In [20]:
np.max(k)#maximum value

19

In [21]:
np.log(k)#logarithm values

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [23]:
np.square(k)#square values

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [27]:
j=np.arange(1.011,20.022)#float values
j

array([ 1.011,  2.011,  3.011,  4.011,  5.011,  6.011,  7.011,  8.011,
        9.011, 10.011, 11.011, 12.011, 13.011, 14.011, 15.011, 16.011,
       17.011, 18.011, 19.011, 20.011])

In [28]:
np.round(j,decimals=2)#round function

array([ 1.01,  2.01,  3.01,  4.01,  5.01,  6.01,  7.01,  8.01,  9.01,
       10.01, 11.01, 12.01, 13.01, 14.01, 15.01, 16.01, 17.01, 18.01,
       19.01, 20.01])

In [31]:
np.std(k)#standerd deviation of k

5.477225575051661

In [32]:
np.var(k)#variance of k

30.0

In [33]:
np.mean(k)#mean of k

10.0

In [34]:
l=np.random.randn(3,4)
l

array([[ 0.34593652, -0.31079423, -0.8388524 ,  0.68353654],
       [-0.08612976, -0.19626995,  0.93470061, -0.5237095 ],
       [-2.56452276, -1.2615106 ,  0.44542416, -1.23875808]])

In [35]:
np.round(l,decimals=2)

array([[ 0.35, -0.31, -0.84,  0.68],
       [-0.09, -0.2 ,  0.93, -0.52],
       [-2.56, -1.26,  0.45, -1.24]])

In [40]:
food=np.array(['idli','dosa','puri','cahpathi'])
np.unique(food)

array(['cahpathi', 'dosa', 'idli', 'puri'], dtype='<U8')

# pandas

In [49]:
import pandas as pd
import numpy as np

In [47]:
lables=['a','b','c','d','e']
sample_list=[10,20,30,40,50]
array=np.array([1,2,3,4,5])
dict={'a':10,'b':20,'c':30,'d':40,'e':50}


In [51]:
pd.Series(data=sample_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [52]:
pd.Series(data=sample_list,index=array)

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [53]:
pd.Series(sample_list,array)

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [54]:
pd.Series(array,lables)#series using the necessary attributres

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [55]:
pd.Series(dict)#series by using dictionary

a    10
b    20
c    30
d    40
e    50
dtype: int64

## pandas dataframe and indexing

In [59]:
sports1=pd.Series([1,2,3,4,5],index=['cricket','vollyball','golf','chess','hockey'])
sports1


cricket      1
vollyball    2
golf         3
chess        4
hockey       5
dtype: int64

In [64]:
sports2=pd.Series([1,2,6,1,5],index=['cricket','vollyball','football','chess','hockey'])
sports2

cricket      1
vollyball    2
football     6
chess        1
hockey       5
dtype: int64

In [65]:
sports1+sports2

chess         5.0
cricket       2.0
football      NaN
golf          NaN
hockey       10.0
vollyball     4.0
dtype: float64

In [70]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='arg1 arg2 arg3 arg4 arg5'.split())
df1

arg1      arg2      arg3      arg4      arg5
A  0.965158  0.417082  0.149166  0.968238  0.885196
B  0.844326  0.807036  0.713113  0.996042  0.534137
C  0.216959  0.699812  0.353106  0.577188  0.669429
D  0.119983  0.876279  0.726704  0.665936  0.643185
E  0.452400  0.658230  0.207298  0.779831  0.847307
F  0.323956  0.296725  0.014824  0.186857  0.452972
G  0.075996  0.699629  0.318932  0.023663  0.101196
H  0.935829  0.377548  0.368924  0.749763  0.595440

In [71]:
df1['arg1']

A    0.965158
B    0.844326
C    0.216959
D    0.119983
E    0.452400
F    0.323956
G    0.075996
H    0.935829
Name: arg1, dtype: float64

In [73]:
df1[['arg1','arg2']]

arg1      arg2
A  0.965158  0.417082
B  0.844326  0.807036
C  0.216959  0.699812
D  0.119983  0.876279
E  0.452400  0.658230
F  0.323956  0.296725
G  0.075996  0.699629
H  0.935829  0.377548

In [77]:
df1['arg6']=df1['arg1']+df1['arg2']
df1

arg1      arg2      arg3      arg4      arg5      arg6
A  0.965158  0.417082  0.149166  0.968238  0.885196  1.382240
B  0.844326  0.807036  0.713113  0.996042  0.534137  1.651362
C  0.216959  0.699812  0.353106  0.577188  0.669429  0.916771
D  0.119983  0.876279  0.726704  0.665936  0.643185  0.996262
E  0.452400  0.658230  0.207298  0.779831  0.847307  1.110630
F  0.323956  0.296725  0.014824  0.186857  0.452972  0.620681
G  0.075996  0.699629  0.318932  0.023663  0.101196  0.775625
H  0.935829  0.377548  0.368924  0.749763  0.595440  1.313377

In [82]:
df2={'id':[101,102,103,104,105],'name':['guna','srinu','bharadwaj','somali','anudeep'],'profits':[1,2,3,4,5]}
df=pd.DataFrame(df2)
df

id       name  profits
0  101       guna        1
1  102      srinu        2
2  103  bharadwaj        3
3  104     somali        4
4  105    anudeep        5

In [84]:
df.drop('id',axis=1)

name  profits
0       guna        1
1      srinu        2
2  bharadwaj        3
3     somali        4
4    anudeep        5

In [91]:
df3=df
df3

id       name  profits
0  101       guna        1
1  102      srinu        2
2  103  bharadwaj        3
3  104     somali        4
4  105    anudeep        5

## how to import dataset

In [98]:
import pandas as pd
import numpy as np

In [104]:
dataframe=pd.read_csv("CardioGoodFitness-1.csv")
dataframe

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     TM195   18    Male         14        Single      3        4   29562   
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [105]:
dataframe.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [107]:
dataframe.shape


(180, 9)

In [109]:
dataframe.tail()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
175   TM798   40   Male         21        Single      6        5   83416   
176   TM798   42   Male         18        Single      5        4   89641   
177   TM798   45   Male         16        Single      5        5   90886   
178   TM798   47   Male         18     Partnered      4        5  104581   
179   TM798   48   Male         18     Partnered      4        5   95508   

     Miles  
175    200  
176    200  
177    160  
178    120  
179    180

In [110]:
dataframe.sample()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
33   TM195   25   Male         16        Single      3        3   43206     85

In [112]:
dataframe.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [113]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [114]:
dataframe.isnull().sum()

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [115]:
dataframe.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [116]:
dataframe.describe(include='all')

Product         Age Gender   Education MaritalStatus       Usage  \
count      180  180.000000    180  180.000000           180  180.000000   
unique       3         NaN      2         NaN             2         NaN   
top      TM195         NaN   Male         NaN     Partnered         NaN   
freq        80         NaN    104         NaN           107         NaN   
mean       NaN   28.788889    NaN   15.572222           NaN    3.455556   
std        NaN    6.943498    NaN    1.617055           NaN    1.084797   
min        NaN   18.000000    NaN   12.000000           NaN    2.000000   
25%        NaN   24.000000    NaN   14.000000           NaN    3.000000   
50%        NaN   26.000000    NaN   16.000000           NaN    3.000000   
75%        NaN   33.000000    NaN   16.000000           NaN    4.000000   
max        NaN   50.000000    NaN   21.000000           NaN    7.000000   

           Fitness         Income       Miles  
count   180.000000     180.000000  180.000000  
unique         NaN            NaN         NaN  
top            NaN            NaN         NaN  
freq           NaN            NaN         NaN  
mean      3.311111   53719.577778  103.194444  
std       0.958869   16506.684226   51.863605  
min       1.000000   29562.000000   21.000000  
25%       3.000000   44058.750000   66.000000  
50%       3.000000   50596.500000   94.000000  
75%       4.000000   58668.000000  114.750000  
max       5.000000  104581.000000  360.000000